#!/bin/bash

Color_Off='\033[0m'
BRed="\033[1;31m"         # Red
BGreen="\033[1;32m"       # Green
BYellow="\033[1;33m"      # Yellow
BBlue="\033[1;34m"        # Blue

COMMIT_MESSAGE="$(cat $1)"
# Initialize constants here
# Regex must be in posix format
export REGEX='^(chore\(release\)?:[[:space:]][0-9]+\.[0-9]+\.[0-9]+)|(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)?:[[:space:]]#id[[:space:]][0-9]+([[:space:]]|[a-z0-9])+[a-z0-9]$'
#export REGEX='.*'
export ERROR_MSG="Commit message must be follow conventional commits rules!! Ex.\"feat: #id 1234 example message\"\nBe sure you are not using the following pattern: [A-Z-,.!|?_^~]"

if [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
  printf "${BGreen}Changes successful committed${Color_Off}"
else
  printf "${BRed}Bad commit ${BBlue}\"$COMMIT_MESSAGE\"\n"
  printf "${BYellow}$ERROR_MSG\n"
  exit 1
fi
exit 0
