#!/bin/bash

BRed="\033[1;31m"         # Red
BYellow="\033[1;33m"      # Yellow
BGreen="\033[1;32m"       # Green

export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
# Regex must be in posix format
export REGEX='(master|(US/PD)-#ID-[0-9]+-[A-Z0-9-]+)'

if ! [[ $BRANCH_NAME =~ $REGEX ]]; then
  printf "${BRed}Your commit was rejected due to branching name${Color_Off}"
  printf "${BYellow}Please rename your branch with the following pattern US/PD-#ID-123-ADD-NEW-FEATURE${Color_Off}"
  exit 1
else
  printf "${BGreen}Branch name is valid.${Color_Off}"
fi

. "$(dirname "$0")/_/husky.sh"
npx lint-staged 
